### PR TITLE
Make the library Composer friendly.

### PR DESCRIPTION
**Pull request by ggioffreda**
Hi,
this is just if you wanted to make it easier for PHP developers to include your library. I've temporary added it on packagist.org under my account so it's available for download but I'll definitely pass it to you if you decide to merge.

Cheers,
Giovanni

### CODE REVIEW

**Comment by davidarias** [comment]
Hi, 

Your changes are most welcome :) Right now I'm finishing some other things, but In a few days I'll merge it. Thanks you very much for you contribution.

**Comment by kpantic** [comment]
Hi @ggioffreda, I'm going to merge this, could you pass the package at https://packagist.org/packages/catchoom/craftar-php to the user 'catchoom'?

**Comment by ggioffreda** [comment]
Hi @kpantic I've added *catchoom* as a maintainer, please confirm that is you and I will remove myself from the list of maintainers. Or feel free to remove me once you log in. Cheers

**Comment by kpantic** [comment]
Thank you @ggioffreda, it is indeed us and we'll be updating the package on Composer now a lot more frequently.

**Pull request merged**
